### PR TITLE
Fix device_role -> role and add testing for Netbox 3.6

### LINKED ISSUE #1061: [Bug]: Breaking changes in 3.6.0, device_role -> role
PR: https://github.com/netbox-community/ansible_modules/pull/1062

### Ansible NetBox Collection version

v3.14.0

### Ansible version

https://github.com/netbox-community/netbox/releases/tag/v3.6.0

> The device_role field on the Device model has been renamed to role. The device_role field has been temporarily retained on the REST API serializer for devices for backward compatibility, but is read-only.

### NetBox version

v3.6.0

### Python version

3.10

### Steps to Reproduce

```
      netbox.netbox.netbox_device:
        data:
          name: "{{ ansible_facts['product_name'] }}"
          device_type: "{{ ansible_facts['product_name'] }}"
          device_role: 1
          site: 1
        state: present

```

### Expected Behavior

Device is created/updated

### Observed Behavior

```
{"role":["This field is required."]}
fatal: [10.0.20.10 -> localhost]: FAILED! => {
    "changed": false
}
```

### PR DESCRIPTION
**Pull request by FragmentedPacket**
## Related Issue
`device_role` was renamed to `role` within the Netbox API for v3.6+
Filter for IP Addresses now require `virtual_chassis_member_id` to fetch VC member interfaces and `device_id` no longer returns the VC member interfaces.

Fixes #1061

## New Behavior

Compatibility with Netbox APIs but no user changes need to occur.

## Proposed Release Note Entry

Fix `device_role` being renamed to `role` in Netbox 3.6+ API
Change query params for searching interfaces when we need to find the VC member interfaces.

### CODE REVIEW

**Comment by rodvand** [comment]
Could we merge the device_role fix and handle the VC issue in a different PR?

**Comment by FragmentedPacket** [comment]
> Could we merge the device_role fix and handle the VC issue in a different PR?

I fixed that one as well. There apparently is more breaking changes around IP addresses or maybe it's the code. I will leave this alone for now and keep those two fixes in while you review.

**Review by rodvand — APPROVED** [review]

**Comment by sag2643** [comment]
facing issues with the role msg": "{\"role\":[\"This field is required.\"]}"} , may i know if this has been fixed ?

**Comment by ma9icmarker** [comment]
do you know when this will be rolled into the next release?

**Comment by jonatangobbato** [comment]
> do you know when this will be rolled into the next release?

@rodvand  Is there any way to get around the problem for now until the next release?

**Pull request merged**
