### PR TITLE
Fix for mapping between power_outlet_template and power_port_template

### PR DESCRIPTION
**Pull request by toerb**
This is a work in progress.
Target is to fix the reference from a power_outlet_template to a power_port_template.

### CODE REVIEW

**Comment by toerb** [comment]
Hi @FragmentedPacket,

this PR will change the parameter ´power_port´ of ´netbox_power_outlet_template´ to ´power_port_template´.
Additionally it will add some logic to map between a `power_outlet` and a `power_port`.

I have not written an issue about this topic but it has affected me in my try to generate PDUs as a device type.
If you need an issue to merge then just drop a message and I'll write one in the next days.

Best regards
toerb

**Comment by FragmentedPacket** [comment]
Thanks @toerb. I will try and review this before the end of the weekend.

Thanks again for your contributions!

**Comment by toerb** [comment]
Hi @FragmentedPacket, is there any news on this PR? Just tell me if I have to adapt something.

**Comment by FragmentedPacket** [comment]
@toerb Do you mind fixing the conflict and then we'll get this merged in?

**Comment by toerb** [comment]
@FragmentedPacket, merge is done. Can you tell me something about the broken CI task? The log isn't telling me much.

**Comment by FragmentedPacket** [comment]
It looks like 2.11 probably adds the `count_ip_addresses` or whatever it is.

We're good to merge this! Thanks for your work!

**Pull request merged**
