### PR TITLE
docs: NetBox should be referred to as NetBox

### PR DESCRIPTION
**Pull request by ypid**
This fixes all occurrences of "Netbox".

Ref: https://netbox.readthedocs.io/en/stable/development/style-guide/#branding

[DATALAD RUNCMD] git ls-files -z . | xargs --null -I '()'...

```json
{
 "chain": [],
 "cmd": "git ls-files -z . | xargs --null -I '()' find './()' -type f -print0 | xargs --null sed --in-place --regexp-extended 's/\\bNetbox\\b/NetBox/g;'",
 "exit": 0,
 "extra_inputs": [],
 "inputs": [],
 "outputs": [],
 "pwd": "."
}
```

### CODE REVIEW

**Review by 2bithacker — DISMISSED** [review]

**Review by 2bithacker — APPROVED** [review]

**Comment by ryanmerolle** [comment]
@ypid thanks for this.  Our team has been behind quite a bit on PRs, but happy to review this.  Could you please fix the current branch conflicts?

**Comment by ypid** [comment]
Done that.

**Comment by ypid** [comment]
I rerun the mechanical edit against the latest master. My change is quite big which makes merge conflicts likely whenever master is updated. Can you consider merging this PR?

**Review by sc68cal — APPROVED** [review]

**Comment by devon-mar** [comment]
Thee description on GitHub for this repo still uses `Netbox` as well.

**Comment by sc68cal** [comment]
> Thee description on GitHub for this repo still uses `Netbox` as well.

Fixed

**Comment by sc68cal** [comment]
@rodvand Thoughts on merging this?

**Pull request merged**
