### PR TITLE
Update module to work with pynetbox 5.0

### PR DESCRIPTION
**Pull request by smutel**
Fix issue #248

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
In the `.travis.yml` we hard-coded the `pynetbox` to `4.3.3` to work around this issue. Do you mind removing the pinned version and just let it install the latest and I think the tests will hopefully pass.

If that doesn't fix it, I will have to do some research around the testing error.

**Comment by FragmentedPacket** [comment]
It may also require the import of requests to be right below the attempt of importing `pynetbox` after looking into this a bit further since it's a 3rd party package.

**Comment by smutel** [comment]
I add a pip list in https://travis-ci.com/github/netbox-community/ansible_modules/jobs/359616773 and we can see that request is correctly installed. I don't understand why the ci is not passing. I will continue to investigate ...

**Comment by FragmentedPacket** [comment]
I may take this over but I think if you move the import of request into where pynetbox is, some of the issues will be fixed

**Comment by FragmentedPacket** [comment]
I've fixed some of the stuff, but I think in the 5.0.0 release, it changed how it returned the available_ips and prefixes so have to fix that as well.

I will most likely close this one out once I have it fixed, but make sure to credit you.

I also appreciate your effort on this and the communication on both this project and `pynetbox`, it is greatly appreciated!

**Comment by FragmentedPacket** [comment]
Made a few updates with other changes involved with pynetbox >=5.0.0 on #269 

Thanks a lot for your work @smutel !

**Pull request closed without merging**
