### PR TITLE
Multiple prefix per site - BUG #732

### PR DESCRIPTION
**Pull request by Eric-Sim**
## New Behavior

...

## Contrast to Current Behavior

...

## Discussion: Benefits and Drawbacks

...

## Changes to the Documentation

None

## Proposed Release Note Entry

Inventory module now properly includes the full list of prefixes assigned to a site.

## Double Check

* [ X ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ X ] I have explained my PR according to the information in the comments or in a linked issue.
* [ X ] My PR targets the `devel` branch.

### CODE REVIEW

**Comment by Eric-Sim** [comment]
I think that 3.5.1 (about a month ago) is the only release that includes the site data and prefixes, so people who are using that version definitely could have seen the singular "prefix" data in their inventory.

Any potential user who has built a workflow around having the singular "prefix" attribute nested within site data is going to  be disrupted by this fix. 

That being said, my thinking was that it would actually be better to have those users error out by trying to grab a key that no longer exists (which they would investigate and quickly figure out). The alternative, it that they continue to being able to access the same key, but be returned a different data structure. (This way may be more difficult for someone to notice and troubleshoot if they don't pay close attention to release notes)

**Comment by rodvand** [comment]
I'm thinking it could go in as a bug fix... the functionality has not worked the way it's supposed to be so anyone currently using it is getting a half-working solution.

**Comment by Eric-Sim** [comment]
I'd agree with calling it a bug fix.
I'll defer to you guys on how you'd like this to be dealt with though.

**Review by rodvand — APPROVED** [review]

**Comment by sc68cal** [comment]
I think we should call it out in the release notes that the key has changed from `prefix` to `prefixes` - just to close the loop.

**Pull request merged**
