### PR TITLE
Add custom headers to inventory request

### PR DESCRIPTION
**Pull request by bloomcake**
## New Behavior

* Add custom headers to inventory request

## Contrast to Current Behavior

New `headers` are appended to `self.headers` to be able to add own headers.

## Discussion: Benefits and Drawbacks

...

## Changes to the Documentation

...

## Proposed Release Note Entry

Add custom headers to inventory request

## Double Check

* [x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [x] I have explained my PR according to the information in the comments or in a linked issue.
* [x] My PR targets the `devel` branch.

### CODE REVIEW

**Review by sc68cal — CHANGES_REQUESTED** [review]
This should be managed via the standard `HTTP_PROXY` environment variable - https://docs.ansible.com/ansible/2.4/playbooks_environment.html

**Comment by sc68cal** [comment]
pynetbox under the hood uses `requests` - which honors the standard `HTTP_PROXY` environment variable and others

https://requests.readthedocs.io/en/latest/user/advanced/?highlight=HTTP_PROXY#proxies

**Comment by sc68cal** [comment]
Basically, I don't want us to have code in our repository that deals with however you've deployed netbox in your environment. There are generally accepted practices for setting up proxies, we have a couple of users who have reported their usage of netbox behind a proxy. You should configure an HTTP(s) proxy, instead of adding code that sets a cookie and make everyone else who ever uses this code support that.

**Comment by clinta** [comment]
Sadly found this issue trying to figure out how to use this plugin with netbox behind Cloudflare zero trust. I'm not sure how an outbound http proxy is supposed to replace the ability to add custom headers.

**Comment by sc68cal** [comment]
See the linked issue 895, user was using a custom proxy solution which required a custom header to be set in order to work with their proxy setup. I don't wish for us to carry the burden of maintaining how people set up proxies between the various NetBox components (both API clients and the netbox server), since it also has been a source of bug reports where we don't really have a way of fixing it since it's unique to each user's environment.

**Comment by clinta** [comment]
I can understand that for a complex change. But this change is literally one line of (of non-documentation). Also this functionality is explicitly supported by pynetbox, and [documented](https://pynetbox.readthedocs.io/en/latest/advanced.html#headers). The implementation does not have any specific logic for dealing with specific proxies, it's just the generic ability to add any headers the user needs. 

I've rebased this PR to run my own fork, and added the same functionality to the lookup module. I'd ask you to reconsider and look at what a small change this is.

https://github.com/netbox-community/ansible_modules/compare/master..clinta:custom_headers

**Comment by sc68cal** [comment]
OK, that is a convincing argument to me. Open a PR. I'll :+1:

**Pull request closed without merging**
