### PR TITLE
netbox_inventory_item: Allow assigning a component

### PR DESCRIPTION
**Pull request by btriller**
## New Behavior

Allow assigning a component to an inventory_item.

## Contrast to Current Behavior

...

## Discussion: Benefits and Drawbacks

Benefit: Users can optionally assign the component to an inventory_item.
Drawbacks: None

## Changes to the Documentation

Documentation for the new parameters are included in the PR.

## Proposed Release Note Entry

...

## Double Check

* [x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [x] I have explained my PR according to the information in the comments or in a linked issue.
* [x] My PR targets the `devel` branch.

### CODE REVIEW

**Review by sc68cal — CHANGES_REQUESTED** [review]
Needs a unit test

**Comment by ahlee1** [comment]
@btriller I apologize if this is inappropriate since I'm still new to contributing but I noticed this PR has been open for sometime. I'd like to have this feature in the next version so perhaps I can help by completing the unit tests. Cheers

**Comment by sc68cal** [comment]
@ahlee1 haven't seen the original author come back, so please do feel free to open a new PR that incorporates these changes and unit tests that you write.

**Comment by rodvand** [comment]
This has been completed in #1078

**Pull request closed without merging**
