### PR TITLE
Fix: More than one result returned for virtual_chassis

### LINKED ISSUE #402: Add devices to virtual chassis error -> "More than one result returned for virtual_chassis"
## Environment
- Docker NetBox-Docker version: 0.27.0
- Ansible Netbox.netbox collection: 1.2.0
- Python PyNetbox: 5.1.2
- Python Ansible-base: 2.10.4
- NetBox version: 2.9.9 (worked) & 2.10.2 (bugged)

Adding devices to a virtual chassis through the Ansible netbox.netbox collection gives an error on the second device/chassis added to the same virtual chassis: "More than one result returned for virtual_chassis". Error first seen in version 2.10.2, Downgraded to version 2.9.9 and confirmed to be working.

Sample inventory:
```
    SWITCH-001:
      ansible_host: 10.10.10.1
      device_role: Access Switch
      device_chassis:
        - type: OS6560-P48X4
          unit: 1
        - type: OS6560-P48X4
          unit: 2
        - type: OS6560-P48X4
          unit: 3
```

Playbook:
```
   - name: Create virtual chassis
      netbox_virtual_chassis:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: '{{ inventory_hostname }}'
          master: '{{ inventory_hostname + "-1" }}'
        state: present
```

```
    - name: Add devices to Virtual chassis
      netbox_device:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: '{{ inventory_hostname + "-" + item.unit|string }}'
          virtual_chassis: '{{ inventory_hostname }}'
          vc_position: '{{ item.unit}}'
      loop: '{{ device_chassis  }}'
```

## Steps to Reproduce
- Ansible: add device through netbox.netbox.netbox_device module
- Ansible: create virtual chassis through netbox.netbox.netbox_virtual_chassis module
- Ansible: update devices to add them to virtual chassis through netbox.netbox.netbox_device module

**What did you expect to happen?**
One virtual chassis with three added chassis/devices linked

**What happened instead?**
Netbox version 2.9.9: worked fine
Netbox version 2.10.2: Ansible error and only two chassis/devices added to virtual chassis.

### LINKED ISSUE #502: Add netbox_site_group module
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

2.11

##### SUMMARY

Site groups were added in netbox 2.11 and a module `netbox_site_group` should be created to be able to add, update, and delete site groups in netbox. E.g:

```yaml
- name: Add site group
  netbox.netbox.netbox_site_group:
    data:
      name: site group
      parent_site_group: parent site group
      description: this is a site group
    state: present

- name: Delete site group
  netbox.netbox.netbox_site_group:
    data:
      name: site group
    state: absent
```

### PR DESCRIPTION
**Pull request by jefvantongerloo**
Fixes #402 -> More than one result returned for virtual_chassis

**Task:**
```yaml
    - name: NetBox - Create virtual chassis
      netbox_virtual_chassis:
        netbox_url: '{{ netbox_url }}'
        netbox_token: '{{ netbox_token }}'
        data:
          name: '{{ inventory_hostname }}'
          master: '{{ inventory_hostname + "-1" }}'
        state: present
```

**Virtual chassis creation error:***
```yaml
TASK [NetBox - Create virtual chassis] *********************************************************************************************************************************************************
fatal: [NET-LIT-SWI-001]: FAILED! => changed=false 
  msg: More than one result returned for NET-LIT-SWI-001
fatal: [NET-LIT-SWI-DIST]: FAILED! => changed=false 
  msg: More than one result returned for NET-LIT-SWI-DIST
```

**Output after fix:**
```yaml
PLAY [Netbox add devices from inventory] *******************************************************************************************************************************************************

TASK [NETBOX >> query devices before] **********************************************************************************************************************************************************
ok: [NET-SWI-DIST]
ok: [NET-SWI-001]

TASK [NETBOX >> Create devices] ****************************************************************************************************************************************************************
changed: [NET-SWI-001] => (item=OS6560-P48X4)
changed: [NET-SWI-DIST] => (item=OS6860E-P24)
changed: [NET-SWI-001] => (item=OS6560-P48X4)
changed: [NET-SWI-001] => (item=OS6560-P48X4)
changed: [NET-SWI-001] => (item=OS6560-P48X4)

TASK [NetBox - Create virtual chassis] *********************************************************************************************************************************************************
changed: [NET-SWI-DIST]
changed: [NET-SWI-001]

TASK [NetBox - Add devices to Virtual chassis] *************************************************************************************************************************************************
ok: [NET-SWI-DIST] => (item={'type': 'OS6860E-P24', 'unit': 1})
ok: [NET-SWI-001] => (item={'type': 'OS6560-P48X4', 'unit': 1})
changed: [NET-SWI-001] => (item={'type': 'OS6560-P48X4', 'unit': 2})
changed: [NET-SWI-001] => (item={'type': 'OS6560-P48X4', 'unit': 3})
changed: [NET-SWI-001] => (item={'type': 'OS6560-P48X4', 'unit': 4})

TASK [NETBOX >> query devices after] ***********************************************************************************************************************************************************
ok: [NET-SWI-001]
ok: [NET-SWI-DIST]

TASK [NETBOX >> devices list added] ************************************************************************************************************************************************************
ok: [NET-SWI-DIST] => 
  msg:
  - NET-SWI-001-1
  - NET-SWI-001-2
  - NET-SWI-001-3
  - NET-SWI-001-4
  - NET-SWI-DIST-1
ok: [NET-SWI-001] => 
  msg:
  - NET-SWI-001-1
  - NET-SWI-001-2
  - NET-SWI-001-3
  - NET-SWI-001-4
  - NET-SWI-DIST-1

PLAY RECAP *************************************************************************************************************************************************************************************
NET-SWI-001            : ok=6    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
NET-SWI-DIST           : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### CODE REVIEW

**Comment by richardjohnallsopp** [comment]
Can anyone tell me when this will be reviewed and merged please?

**Comment by jefvantongerloo** [comment]
Tested on Netbox version 3.0.0 and issue still present.

**Review by sc68cal — APPROVED** [review]

**Review by sc68cal — CHANGES_REQUESTED** [review]
I'm a little unclear on this. You remove the part of the code that retrieves the `master` setting from the YAML you create, yet you still have it in your first example. 

I haven't used virtual_chassis myself, so I'm a little unclear on what is going on here. It just looks like you removed the part of the code that used `master` attribute.

**Comment by rodvand** [comment]
@jefvantongerloo I had to do some changes to the VC module in a different PR - could you check if this is still an issue?

**Pull request closed without merging**
