### PR TITLE
CI Updates

### PR DESCRIPTION
**Pull request by ryanmerolle**
## New Behavior

- Split linting into its own stage (commented out ruff and isort for future)
- Removed NetBox v3.1 test files
- Bumped python version to 3.9 (removed python3.8)
- Applied a fix for netbox-docker timeouts
- Updated GitHub action versions
- Various yaml lint related updates
- Correct project.toml version to current project version
- Removed code duplication in GitHub CI/Actions
- Prepared for python3.11 & ansible-core 2.14 (ansible-core 2.14 breaks integration_testing)
- Prepared for python 3.10 and python 3.11 matrix testing in integration_testing

## Contrast to Current Behavior

...

## Discussion: Benefits and Drawbacks

I tried to get ready for the requirements of testing with ansible-core 2.14, but it breaks integration tests when I bump the package in poetry from 2.13.

## Changes to the Documentation

...

## Proposed Release Note Entry

...

## Double Check

* [X] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [X] I have explained my PR according to the information in the comments or in a linked issue.
* [X] My PR targets the `devel` branch.

### CODE REVIEW

**Comment by ryanmerolle** [comment]
Please squash and merge if you would like this to be merged.

**Comment by ryanmerolle** [comment]
I need to investigate readthedocs error.

**Comment by ryanmerolle** [comment]
Fixed the readthedocs issue per https://github.com/readthedocs/readthedocs.org/issues/10290

**Review by sc68cal — APPROVED** [review]
Looks good. Do you want to squash & merge this to make the history a little simpler?

**Pull request merged**
