### PR TITLE
Remove pre-NetBox 3.3 features

### PR DESCRIPTION
**Pull request by hollow**
## Related Issue

https://github.com/netbox-community/pynetbox/pull/521

## Contrast to Current Behavior

Support for secrets has been removed

## Proposed Release Note Entry

Support for secrets has been removed

## Double Check

* [x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [x] I have explained my PR according to the information in the comments or in a linked issue.
* [x] My PR targets the `devel` branch.

### CODE REVIEW

**Comment by rodvand** [comment]
Secrets is actually a pre 3.0 feature so I think it is safe to remove this now. We do however need to mark the option as deprecated in the module, not just remove it.

**Comment by hollow** [comment]
@rodvand I wasn't sure about the required process so I started by simply removing it, since the update to pynetbox 7.x today broke my ansible playbooks 🙈

**Comment by sc68cal** [comment]
This brings up a question, should we be putting constraints on our dependencies, like pynetbox, since they do make API changes that break things?

**Comment by bluikko** [comment]
@sc68cal Definitely!
Even better would be if these 2 projects would coordinate together since they are totally intertwined.

This change has broken everyone's netbox.netbox...

**Comment by jefvantongerloo** [comment]
Following.

Can confirm, pynetbox upgrade broke my calls through nb_lookup modules.
Found a solution in downgrading to 6.6.2.

It would be great to synchronise the pynetbox requirement to assure compatibility with each netbox collection and netbox version release.

**Comment by ryanmerolle** [comment]
releates to #878

**Pull request closed without merging**
