### PR TITLE
Netbox Inventory Plugin

### PR DESCRIPTION
**Pull request by loganbest**
Pulled the Inventory Plugin netbox.py from ansible/ansible:devel and updated names to reflect collections namespacing so it works. All existing functionality has been manually tested on Ansible 2.9.1 and 2.9.2

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
Could you possibly push another commit to this? Maybe a minor doc change. Travis-ci should be working.

**Comment by FragmentedPacket** [comment]
Do you mind rebasing from `devel` and then seeing if it will start testing on travis-ci?

**Comment by loganbest** [comment]
Black failed on it. I'll fix that in a sec a commit

**Comment by loganbest** [comment]
Aye. All passed :)

**Pull request merged**
