### PR TITLE
feat: inventory item component

### PR DESCRIPTION
**Pull request by ahlee1**
## Related Issue

Lots of thanks to @btriller for the majority of the work on this PR
Previous PR for this: https://github.com/netbox-community/ansible_modules/pull/1020

## New Behavior

Allows assigning a component to an inventory item

## Contrast to Current Behavior

We cannot assign a component to an inventory item

## Discussion: Benefits and Drawbacks

Benefit: Users can optionally assign the component to an inventory_item.
Drawbacks: 
- It is not possible to update a created item with a component as we use components in the ALLOWED_QUERY_PARAMS
  ex: If you create item1 with no components and try again with components it will create a new inventory item.

## Proposed Release Note Entry

Allow the assignment of components to inventory items

## Double Check

* [x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [x] I have explained my PR according to the information in the comments or in a linked issue.
* [x] My PR targets the `devel` branch.

### CODE REVIEW

**Review by sc68cal — DISMISSED** [review]
Code looks good, re-running the failing job, it looked transient

**Comment by ahlee1** [comment]
> Code looks good, re-running the failing job, it looked transient

I believe this carries over from this PR https://github.com/netbox-community/ansible_modules/pull/1066#issuecomment-1713095570

**Comment by ahlee1** [comment]
Sorry for the last minute pushes, noticed the name weren't right for the tests.

**Comment by sc68cal** [comment]
The CI failure appears to be unrelated to your change. It appears something got merged that broke the tests. Investigating.....

**Comment by ahlee1** [comment]
@sc68cal When I looked into it, the issue seems to be from netbox itself when they changed the way available ips are structured. https://github.com/netbox-community/netbox/issues/13746

**Pull request merged**
