### PR TITLE
switch from ansible-base to ansible-core 

### LINKED ISSUE #583: CI does not run sanity tests with ansible-core 2.11 and ansible-core's devel branch
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It currently only runs these tests with ansible-base 2.10, which is not a good idea at all.

Check out the testing requirements for inclusion in Ansible: https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing

### PR DESCRIPTION
**Pull request by ryanmerolle**
Closes #583

### CODE REVIEW

**Review by sc68cal — APPROVED** [review]

**Comment by sc68cal** [comment]
🤞

**Comment by ryanmerolle** [comment]
A lot more CI work will be needed as we need to test vs ansible-core 2.11 and ansible-core devel.

Moving to ansible-core 2.11 will potentially require a bunch of work:
https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing

Given nautbot & nautobot ansible collection is just a fork of NetBox and NetBox Ansible collection, we likely can use this for guidance: https://github.com/nautobot/nautobot-ansible/pull/66/files

**Comment by ryanmerolle** [comment]
@daniel-wtd any experience with the new ansible-core unit test and sanity requirements to assist in the unblock?  I was able to get current CI state unblocked over the weekend with #573 , but I'm not sure I can get this sorted this week or this weekend.  My notes in this PR and frankly the notes from #583 should be enough to get your started.  You can also likely reach out to @FragmentedPacket if you are really nice to discuss his experience with the nautobot PR I linked.

**Comment by ryanmerolle** [comment]
closed in favor of #591

**Pull request closed without merging**
