### PR TITLE
fixing bug #975

### PR DESCRIPTION
**Pull request by Ido-Don**
## Related Issue

The issue this PR is trying to fix is #975 

## New Behavior

this pull request changes the data object to include the assigned_object_id and assigned_object_type values.
it takes the interface_id that exists in the interface value and adds an assigned_object_id and an assigned_object_type item.

## Contrast to Current Behavior

the current behavior will not assign an IP to the interface.

## Discussion: Benefits and Drawbacks

This bug prevents the assigning of an IP to an interface.
it is backwards compatible.

It is worth noting that there is a duplication between the assigned_object and interface values.
In my opinion it is best to deprecate the interface value internally and make people use only the assigned_object value.

## Changes to the Documentation

the documentation already states this functionality, it was not implemented but it should have.

## Proposed Release Note Entry

netbox_ip_address - Fixed the problem preventing assignment of an IP address to a network interface

## Double Check

* [x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [x] I have explained my PR according to the information in the comments or in a linked issue.
* [x] My PR targets the `devel` branch.

### CODE REVIEW

**Comment by sc68cal** [comment]
This looks good to me, just needs a changelog put into the `fragments` directory and then maybe a test to verify the behavior?

**Comment by Ido-Don** [comment]
I added the tests and fragment to the PR.
Should i open an issue so we could discuss the deprecation of the interface value?

**Review by sc68cal — APPROVED** [review]
Thank you for the contribution!

**Comment by sc68cal** [comment]
>  Should i open an issue so we could discuss the deprecation of the interface value?

Yes please do

**Comment by Ido-Don** [comment]
> > Should i open an issue so we could discuss the deprecation of the interface value?
> 
> Yes please do

I opened issue #1338, you are welcome to come and take a look 😁

**Comment by Ido-Don** [comment]
> Thank you for the contribution!

Thank you for reviewing my code!
now all that i need is to marge the changes 😄

**Pull request merged**
