### PR TITLE
Copy interfaces before processing in extractor

### LINKED ISSUE #535: nb_inventory fails to cache network interfaces if tags are set for any interface of that host
##### ISSUE TYPE

 - Bug Report

###### Ansible:
2.10.10

###### Netbox:
2.11.4

###### Collection:
3.1.1

##### SUMMARY
When a (virtual) machine has a network interface that has tags attached to it, the whole "interfaces" information is not cached by ansibles inventory cache.

##### STEPS TO REPRODUCE

- activate caching for netbox.nb_inventory (cache_plugin: "jsonfile", cache: yes)
- add a virtual host "test" to netbox
- add interfaces to that host
- set a tag on one of those interfaces
- `ansible -a msg="{{ interfaces }}" -m debug  test` for the first time will output interfaces
- running the same for a second time, will output "[..] 'interfaces' is undefined"
- now clean the cache and run again
- now remove the tag from the interface and clean the cache, then run again as often you like

##### EXPECTED RESULTS

Cached information should be consistent with uncached information

##### ACTUAL RESULTS

Results were different depending on if cache was used or not

### PR DESCRIPTION
**Pull request by nahun**
Fixes #535.

The interfaces extractor modifies the inventory as it processes the tags. Copy the interfaces list first instead.

### CODE REVIEW

**Comment by TWitzenrath** [comment]
works perfectly, cant wait to see this merged :heart_eyes_cat:

**Comment by ryanmerolle** [comment]
Hello @philfry I asked @nahun to fetch upstream for the latest updates we added to the repo for 3.1.2.  After the new CI completes, I am assuming it will complete successfully, can you please test for your issue?

You can install his PR by:
```
ansible-galaxy collection install -f git+https://github.com/nahun/ansible_modules.git,fix_535
```

Assuming all goes well, we can get it released today or tomorrow.

**Comment by philfry** [comment]
Hi @ryanmerolle, thanks! I'll test it asap tomorrow :)

**Comment by philfry** [comment]
Hi,
I tested it successfully, works like a charm.
:+1:

**Review by ryanmerolle — APPROVED** [review]
LGTM

**Pull request merged**
