### PR TITLE
draft: Linting Updates

### PR DESCRIPTION
**Pull request by ryanmerolle**
## New Behavior

- Add linter (black, isort, ruff) settings to `project.toml`
- Enable additional github action workflows for linting
- auto-fixed isort, json (pretty format), black, ruff, yamllint, end of file new line, trailing spaces removal
- Added pre-commit config
- Added invoke workflow to call common tasks (linter focused for now, more coming)
- Add explicitly encoding where missed in python open

## Contrast to Current Behavior

Minimal linting & convenience functionality for local development.

## Changes to the Documentation

Doc updates with regards to contributing forthcoming

## Proposed Release Note Entry

TBD

...

## Double Check

* [X] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [X] I have explained my PR according to the information in the comments or in a linked issue.
* [X] My PR targets the `devel` branch.

### CODE REVIEW

**Comment by ryanmerolle** [comment]
I'll update docs after I get feedback for this draft

**Comment by ryanmerolle** [comment]
I'll look into tests shortly, just rather get feedback on the approach.

**Review by sc68cal — COMMENTED** [review]
Looks good, my only pet peeve about black and pep8 reformatting is that it makes it harder to use `git blame` for meaningful changes, but oh well.

**Comment by ryanmerolle** [comment]
That’s 100% fair.  The point of it is so that longer term people use the same format rules and so you do not get diffs due to personal style.  Frankly, we never started with black from the start, so I’d be fine to drop it while applying the other linting.

**Comment by sc68cal** [comment]
It's fine. I just felt obligated to complain about it, but I agree with the changes

**Review by sc68cal — APPROVED** [review]

**Comment by rodvand** [comment]
I'm gonna close this as there's been some more recent work related to the certification process.

**Pull request closed without merging**
